name: Build Android APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build APK with Buildozer Action
        uses: SubhrajitPrusty/buildozer-action@v1.2.4
        with:
          command: buildozer -v android debug
          subpath: '.'

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MyStudioPro-APK
          path: bin/*.apk
